FROM node:22-alpine

WORKDIR /app

RUN npm install -g json-server@0.17.4

COPY db.json json-server.json ./

EXPOSE 3001

CMD ["json-server", "--host", "0.0.0.0", "--port", "3001", "--watch", "db.json"]
