services:
  mf-transacoes:
    build:
      context: ./mf-transacoes
      dockerfile: Dockerfile
      additional_contexts:
        shared: ./shared
    ports:
      - '4200:80'

  mf-dashboard:
    build:
      context: ./mf-dashboard
      dockerfile: Dockerfile
      additional_contexts:
        shared: ./shared
    ports:
      - '4300:80'

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3001
        NEXT_PUBLIC_MF_TRANSACOES_URL: http://localhost:4200
        NEXT_PUBLIC_MF_DASHBOARD_URL: http://localhost:4300
    ports:
      - '3000:3000'
    environment:
      API_URL: http://host.docker.internal:3001
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_MF_TRANSACOES_URL: http://localhost:4200
      NEXT_PUBLIC_MF_DASHBOARD_URL: http://localhost:4300
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - mf-transacoes
      - mf-dashboard
